on:
  workflow_dispatch:

jobs:
  example-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'sbt'

      - name: Get version
        run: |
          a=$(sbt 'root/version' | tail -n 1 | cut -d ' ' -f 2  | xargs)
          echo $a
        env:
          ACTIONS_STEP_DEBUG: true
