name: publish api docker image

on:
  workflow_dispatch:
    inputs:
      latest:
        description: 'whether release latest docker image'
        type: choice
        default: 'false'
        options:
          - true
          - false

permissions:
  contents: write
  packages: write

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: login to gcr
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: publish api docker image
        run: |
          echo "release latest image ${{ inputs.latest }}"
          if [[ "${{ inputs.latest }}" != "false" ]]; then
            echo "latest"
            # sbt -Ddocker.image.version=latest "project api" docker:publish
          else
            echo "non latest"
            # sbt "project api" docker:publish
          fi