name: publish api docker image

on:
  workflow_dispatch:

permissions:
  contents: write
  packages: write


jobs:
  publish:
    runs-on: ubuntu
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: login to gcr
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: publish docker image
        run: sbt docker:publish