name: Release packages

on:
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'sbt'

      - name: build zip
        run: sbt universal:packageBin

      - name: get version
        run: |
          project_version=$(sbt 'root/version' | tail -n 1 | cut -d ' ' -f 2)
          echo "current project version: $project_version"
          echo "PROJECT_VERSION=$project_version" >> $GITHUB_ENV

      - name: release cli zip
        uses: ncipollo/release-action@v1
        with:
          artifacts: "cli/target/universal/cli*.zip"
          tag: "rel/" + ${{ env.PROJECT_VERSION }}
          allowUpdates: true

      - name: release api zip
        uses: ncipollo/release-action@v1
        with:
          artifacts: "api/target/universal/api*.zip"
          tag: "rel/" + ${{ env.PROJECT_VERSION }}
          allowUpdates: true

      - name: publish packages
        run: sbt publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
