name: Release packages

on:
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'sbt'

      - name: build zip
        run: sbt universal:packageBin

      - name: release cli zip
        uses: ncipollo/release-action@v1
        with:
          artifacts: "cli/target/universal/cli*.zip"
          name: ${{ vars.RELEASE_VERSION }}
          tag: ${{ vars.RELEASE_VERSION }}
          allowUpdates: true

      - name: release api zip
        uses: ncipollo/release-action@v1
        with:
          artifacts: "api/target/universal/api*.zip"
          name: ${{ vars.RELEASE_VERSION }}
          tag: ${{ vars.RELEASE_VERSION }}
          allowUpdates: true

      - name: publish packages
        run: sbt publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
