name: Release packages

on:
  workflow_dispatch:

permissions:
  contents: write
  packages: write

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'sbt'

      - name: Setup sbt
        uses: sbt/setup-sbt@v1

      - name: Build zip
        run: sbt universal:packageBin

      - name: Get version
        run: |
          project_version=$(grep "projectVersion\s*=" build.sbt | awk -F'"' '{print $2}')
          echo "current project version: $project_version"
          echo "TAG=rel/$project_version" >> $GITHUB_ENV

      - name: Release cli zip
        uses: ncipollo/release-action@v1
        with:
          artifacts: "cli/target/universal/cli*.zip"
          tag: ${{ env.TAG }}
          allowUpdates: true

      - name: Release api zip
        uses: ncipollo/release-action@v1
        with:
          artifacts: "api/target/universal/api*.zip"
          tag: ${{ env.TAG }}
          allowUpdates: true

      - name: Publish packages
        run: sbt publish
